Olympiad/urls.py
from django.conf.urls import url, include

from olympiad_manager.urls import olympiad_urlpatterns
from olympiad_manager.views.problem import GradeView
from scholar.views import RegisterOlympiad
from ysc.views import HomeView, LogoutView, RegisterView, LoginView

urlpatterns = [
    url(r'^olympiad/(?P<fname>[^/]*)/(?P<year>\d+)/', include(olympiad_urlpatterns, namespace='olympiad')),
    url(r'^', include('dbadmin.urls', namespace='dbadmin')),
    url(r'^', include('scholar.urls', namespace='scholar')),
    url(r'^', include('ysc.urls', namespace='ysc')),
    url(r'^grade/(?P<eid>\d+)/(?P<pnum>\d+)/$', GradeView.as_view(), name='grade'),
]

ysc/urls.py
from django.conf.urls import url

from ysc.views import LogoutView, HomeView
from ysc.views import RegisterView, LoginView

urlpatterns =[
    url(r'^signup/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', HomeView.as_view(), name='home'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block static %}
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-rtl.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    <title>
        {% block title %}سامانه المپیاد های علمی{% endblock %}
    </title>
</head>

<body>
            {% for message in messages %}
                <script>alert("{{message}}");</script>
            {% endfor %}

<div class="container">
    <button class="btn btn-info" onclick="location.href='{% url 'ysc:home' %}'">خانه</button>
    {% block content %}
    {% endblock %}
</div>
</body>

</html>