Olympiad/urls.py
from django.conf.urls import url, include

from olympiad_manager.urls import olympiad_urlpatterns
from olympiad_manager.views.problem import GradeView
from scholar.views import RegisterOlympiad
from ysc.views import HomeView, LogoutView, RegisterView, LoginView

urlpatterns = [
    url(r'^olympiad/(?P<fname>[^/]*)/(?P<year>\d+)/', include(olympiad_urlpatterns, namespace='olympiad')),
    url(r'^', include('dbadmin.urls', namespace='dbadmin')),
    url(r'^', include('scholar.urls', namespace='scholar')),
    url(r'^', include('ysc.urls', namespace='ysc')),
    url(r'^grade/(?P<eid>\d+)/(?P<pnum>\d+)/$', GradeView.as_view(), name='grade'),
]

olympiad_manager/urls.py
from django.conf.urls import url, include

from olympiad_manager.views.levels import ManageLevelsView
from olympiad_manager.views.course import AddCourseView, EditCourseView, AddTeachingHourView, \
    TeachingHourListView
from olympiad_manager.views.course import CourseListView
from olympiad_manager.views.home import OlympiadView, RefreshM2, RefreshMedal
from olympiad_manager.views.m1m2date import M1M2Date
from olympiad_manager.views.problem import ProblemListView, AddProblemView, EditProblemView, \
    ManageGraderView, \
    DeleteGraderView, GradeView, ExamResultsView
from olympiad_manager.views.results import ResultsView, Medalsview
from olympiad_manager.views.summer_exam import SummerExamListView, AddSummerExamView, \
    EditSummerExamView

problem_urlpatterns = [
    url(r'^$', ProblemListView.as_view(), name='list'),
    url(r'^results/$', ExamResultsView.as_view(), name='results'),
    url(r'^add/$', AddProblemView.as_view(), name='add'),
    url(r'^(?P<pnum>\d+)/graders/$', ManageGraderView.as_view(), name='graders'),
    url(r'^(?P<pnum>\d+)/graders/delete/$', DeleteGraderView.as_view()),
    url(r'^(?P<pnum>\d+)/$', EditProblemView.as_view(), name='edit'),
]

course_urlpatterns = [
    url(r'^$', CourseListView.as_view(), name='list'),
    url(r'^add/$', AddCourseView.as_view(), name='add'),
    url(r'^(?P<cname>[^/]*)/$', EditCourseView.as_view(), name='edit'),
    url(r'^(?P<cname>[^/]*)/add-teaching-hour/$', AddTeachingHourView.as_view(),
        name='add-teaching-hour'),
    url(r'^(?P<cname>[^/]*)/teaching-hours/$', TeachingHourListView.as_view(),
        name='teaching-hours')
]

summer_exam_urlpatterns = [
    url(r'^$', SummerExamListView.as_view(), name='list'),
    url(r'^add/$', AddSummerExamView.as_view(), name='add'),
    url(r'^(?P<eid>\d+)/$', EditSummerExamView.as_view(), name='edit'),
]

olympiad_urlpatterns = [
    url(r'^$', OlympiadView.as_view(), name='home'),
    url(r'^course/', include(course_urlpatterns, namespace='course')),
    url(r'^summer-exam/', include(summer_exam_urlpatterns, namespace='summer-camp-exam')),
    url(r'^m1m2date/$', M1M2Date.as_view(), name='m1m2date'),
    url(r'^results/$', ResultsView.as_view(), name='results'),
    url(r'^refresh-m2/$', RefreshM2.as_view(), name='refresh-m2'),
    url(r'^refresh-medal/$', RefreshMedal.as_view(), name='refresh-medal'),
    url(r'^medals/$', Medalsview.as_view(), name='medals'),
    url(r'^problem/(?P<eid>\d+)/', include(problem_urlpatterns, namespace='problem')),
    url(r'^levels/$', ManageLevelsView.as_view(), name="levels"),
]

ysc/urls.py
from django.conf.urls import url

from ysc.views import LogoutView, HomeView
from ysc.views import RegisterView, LoginView

urlpatterns =[
    url(r'^signup/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', HomeView.as_view(), name='home'),
]

olympiad_manager/views/course.py
from django.urls import reverse
from django.views.generic import FormView, TemplateView

from Olympiad.helpers import OlympiadMixin, run_query
from olympiad_manager.forms import CourseForm, TeachingHourForm


class CourseListView(OlympiadMixin, TemplateView):
    template_name = 'olympiad/courses.html'

    def get_context_data(self, **kwargs):
        super()
        kwargs['courses'] = run_query('select * from course join human on teacher_id=national_code '
                                      'where fname=%s and year=%s '
                                      'order by cname',
                                      [self.fname, self.year], fetch=True, raise_not_found=False)
        return kwargs


class AddCourseView(OlympiadMixin, FormView):
    template_name = 'olympiad/course.html'
    form_class = CourseForm

    def get_success_url(self):
        return reverse('olympiad:course:list', args=[self.fname, self.year])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'اضافه کردن کلاس'
        return context

    def form_valid(self, form):
        data = form.cleaned_data
        run_query('insert into course(fname, year, cname, minpass, teacher_id, hourly_wage) '
                  'values(%s, %s, %s, %s, %s, %s)',
                  [self.fname, self.year, data['name'], data['minpass'],
                   data['teacher'], data['wage']])
        return super().form_valid(form)


class EditCourseView(OlympiadMixin, FormView):
    template_name = 'olympiad/course.html'
    form_class = CourseForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        self.course = run_query('select * from course where fname=%s and year=%s and cname=%s',
                                [self.fname, self.year, self.kwargs['cname']], fetch=True)[0]
        kwargs['course'] = self.course
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'ویرایش کلاس'
        return context

    def get_success_url(self):
        return reverse('olympiad:course:list', args=[self.fname, self.year])

    def form_valid(self, form):
        data = form.cleaned_data
        run_query('update course set cname=%s, minpass=%s, teacher_id=%s, hourly_wage=%s '
                  'where fname=%s and year=%s and cname=%s',
                  [data['name'], data['minpass'], data['teacher'], data['wage'], self.fname,
                   self.year, self.course['cname']])
        return super().form_valid(form)


class TeachingHourListView(TemplateView):
    template_name = 'olympiad/teaching-hours.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        run_query('select * from course where fname=%s and year=%s and cname=%s and teacher_id=%s ',
                  [kwargs['fname'], kwargs['year'], kwargs['cname'],
                   self.request.session['user']['national_code']], fetch=True)
        context['hours'] = run_query(
            "select st,en,day,en-st as time,(en-st)*hourly_wage as wage from teachinghour natural join course where cname=%s and fname=%s and year=%s",
            [kwargs['cname'], kwargs['fname'], kwargs['year']], fetch=True, raise_not_found=False)
        context['hourly_wage'] = \
        run_query("select hourly_wage from course where cname=%s and fname=%s and year=%s",
                  [kwargs['cname'], kwargs['fname'], kwargs['year']], fetch=True)[0]['hourly_wage']
        context['total_time'] = run_query(
            "select sum(en-st) as sum from teachinghour where cname=%s and fname=%s and year=%s",
            [kwargs['cname'], kwargs['fname'], kwargs['year']], fetch=True)[0]['sum']
        context['total_wage'] = run_query(
            "select sum((en-st)*hourly_wage) as total from course natural join teachinghour where cname=%s and fname=%s and year=%s",
            [kwargs['cname'], kwargs['fname'], kwargs['year']], fetch=True)[0]['total']
        return context


class AddTeachingHourView(OlympiadMixin, FormView):
    template_name = 'olympiad/add_teaching_hour.html'
    form_class = TeachingHourForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hours'] = run_query(
            "select st,en,day,en-st as time,(en-st)*hourly_wage as wage from teachinghour natural join course where cname=%s and fname=%s and year=%s",
            [self.kwargs['cname'], self.kwargs['fname'], self.kwargs['year']], fetch=True, raise_not_found=False)
        context['hourly_wage'] = \
        run_query("select hourly_wage from course where cname=%s and fname=%s and year=%s",
                  [self.kwargs['cname'], self.kwargs['fname'], self.kwargs['year']], fetch=True)[0]['hourly_wage']
        context['total_time'] = run_query(
            "select sum(en-st) as sum from teachinghour where cname=%s and fname=%s and year=%s",
            [self.kwargs['cname'], self.kwargs['fname'], self.kwargs['year']], fetch=True)[0]['sum']
        context['total_wage'] = run_query(
            "select sum((en-st)*hourly_wage) as total from course natural join teachinghour where cname=%s and fname=%s and year=%s",
            [self.kwargs['cname'], self.kwargs['fname'], self.kwargs['year']], fetch=True)[0]['total']
        return context

    def dispatch(self, request, *args, **kwargs):
        self.cname = kwargs['cname']
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('olympiad:course:add-teaching-hour', args=[self.fname, self.year,
                                                                  self.kwargs['cname']])

    def form_valid(self, form):
        data = form.cleaned_data
        run_query("insert into teachinghour(fname,year,cname,st,en,day) values(%s,%s,%s,%s,%s,%s)",
                  [self.fname, self.year, self.cname, data['st'], data['en'], data['day']])
        return super().form_valid(form)

olympiad_manager/views/home.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import Form
from django.http.response import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import FormView

from Olympiad.helpers import OlympiadMixin, run_query


class OlympiadView(SuccessMessageMixin, OlympiadMixin, FormView):
    template_name = 'olympiad/olympiad.html'
    success_message = 'دانش‌پژوهان با موفقیت در بنیاد ملی نخبگان ثبت‌نام شدند'
    form_class = Form

    def get_success_url(self):
        return reverse('olympiad:home', args=[self.fname, self.year])

    def form_valid(self, form):
        scholars = run_query('select scholar_id from m2_accepted where fname=%s and year=%s',
                             [self.fname, self.year], fetch=True, raise_not_found=False)
        for scholar in scholars:
            try:
                run_query('select national_code from bmn where national_code=%s',
                          [scholar['scholar_id']],
                          fetch=True)
            except Http404:
                run_query('insert into bmn(national_code) values(%s)', [scholar['scholar_id']])
        return super().form_valid(form)


class RefreshM2(OlympiadMixin, View):
    def get(self, request, *args, **kwargs):
        run_query('refresh materialized view m2_accepted')
        messages.success(request, 'با موفقیت انجام شد')
        return redirect(to=reverse('olympiad:home', args=[self.fname, self.year]))


class RefreshMedal(OlympiadMixin, View):
    def get(self, request, *args, **kwargs):
        run_query('refresh materialized view summercamp_gold')
        run_query('refresh materialized view summercamp_silver')
        run_query('refresh materialized view summercamp_bronze')
        messages.success(request, 'با موفقیت انجام شد')
        return redirect(to=reverse('olympiad:home', args=[self.fname, self.year]))

olympiad_manager/views/levels.py
from django.views.generic import FormView

from Olympiad.helpers import OlympiadMixin, run_query
from olympiad_manager.forms import LevelForm


class ManageLevelsView(OlympiadMixin,FormView):
    template_name = 'olympiad/levels.html'
    form_class = LevelForm
    def dispatch(self, request, *args, **kwargs):
        self.medalists = run_query("select scholar_id , name from summercamp_silver join human on scholar_id=national_code where year=%s and fname=%s union "
                                   "select scholar_id , name from summercamp_bronze join human on scholar_id=national_code where year=%s and fname=%s",
                                   [kwargs['year'], kwargs['fname'],kwargs['year'],kwargs['fname']],fetch=True, raise_not_found=False)
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['fname'] = self.fname
        kwargs['year'] = self.year
        kwargs['medalists']=self.medalists
        return kwargs

    def form_valid(self, form):
        for medalist in self.medalists:
            id=medalist['scholar_id']
            level=form.cleaned_data[id]
            print(level)
            if(level==''):
                run_query("update scholar set level=null where id=%s",[id])
            else:
                run_query("update scholar set level=%s where id=%s", [level,id])
        return super().form_valid(form)

olympiad_manager/views/m1m2date.py
from django.urls import reverse
from django.views.generic import FormView

from Olympiad.helpers import run_query, OlympiadMixin
from olympiad_manager.forms import M1M2DateForm


class M1M2Date(OlympiadMixin, FormView):
    template_name = 'olympiad/m1m2date.html'
    form_class = M1M2DateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['rname'] = self.fname
        kwargs['yr'] = self.year
        return kwargs

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs['int_list'] = [i for i in range(
            run_query('select count(*) from examday where fname=%s and year=%s',
                      [self.fname, self.year], fetch=True, raise_not_found=False)[0]['count'])]
        return kwargs

    def form_valid(self, form):
        run_query(
            "update exam set edate=%s where eid=(select eid from m1 where fname=%s and year=%s)",
            [form.data['m1_date'], form.data['rname'], form.data['yr']])
        old_count = \
            run_query("select count(*) from examday natural join m2 where fname=%s and year=%s",
                      [form.data['rname'], form.data['yr']], fetch=True)[0]['count']
        counter = 0
        for i in range(int(form.data['m2_day_count'])):
            if form.data['m2_' + str(i) + '_date'] == "":
                continue
            if counter < old_count:
                run_query(
                    "update examday set percentage=%s where fname=%s and year=%s and num=%s",
                    [form.data['m2_' + str(i) + '_darsad'], form.data['rname'], form.data['yr'],
                     counter])
            else:
                run_query(
                    "insert into examday(fname,year,num,percentage) values(%s,%s,%s,%s)",
                    [form.data['rname'], form.data['yr'], counter,
                     form.data['m2_' + str(i) + '_darsad']])
            run_query(
                "update exam set edate=%s where eid=(select eid from examday where fname=%s and year=%s and num=%s)",
                [form.data['m2_' + str(i) + '_date'], form.data['rname'], form.data['yr'], counter])
            counter += 1
        for i in range(counter, old_count):
            run_query(
                "delete from exam where eid=(select eid from examday where fname=%s and year=%s and num=%s)",
                [form.data['rname'], form.data['yr'], i])
        return super().form_valid(form)

olympiad_manager/templates/olympiad/add_teaching_hour.html
{% extends  "olympiad/teaching-hours.html" %}
{% load static%}
{% block title %} اضافه کردن ساعات کاری{% endblock %}
{% block form %}
 <form method="post">
     <h2>اضافه کردن ساعت کاری</h2>
    {% csrf_token %}
     {{ form.as_p }}
     <button class="btn btn-success" type="submit">ثبت</button>
     <a class="btn btn-primary" href="{% url 'olympiad:course:list' fname year%}"> بازگشت </a>
 </form>
{% endblock %}

olympiad_manager/templates/olympiad/course.html
{% extends  "base.html" %}
{% load static%}

{% block content%}
 <form method="post">
     <h1>{{title}}</h1>
    {% csrf_token %}
     {{ form.as_p }}
     <button class="btn btn-success" type="submit">ثبت</button>
     <a href="{% url 'olympiad:course:list' fname year %}">
        <button class="btn btn-primary" type="button">بازگشت</button>
    </a>
 </form>
{% endblock %}

olympiad_manager/templates/olympiad/courses.html
{% extends  "base.html" %}

{% block title %}امتحان{% endblock %}
{% block content%}
    <table class="table table-hover table-striped">
    <thead>
        <th>نام درس</th>
        <th>نام استاد</th>
    </thead>
    <tbody>
    {% for course in courses %}
            <tr>
                <td>
                    <a href="{% url 'olympiad:course:edit' fname year course.cname%}">
                        {{ course.cname }}
                    </a>
                </td>
                <td>
                    {{ course.name }}
                </td>
                <td>
                    <a class="btn btn-default" href="{% url 'olympiad:course:add-teaching-hour' fname year course.cname %}"> اضافه کردن ساعت تدریس</a>
                </td>
            </tr>
    {% endfor %}
    </tbody>
    </table>
        <a href="{% url 'olympiad:course:add' fname year%}"><button type="button" class="btn btn-success">کلاس جدید</button></a>
    <a href="{% url 'olympiad:home' fname year %}">
        <button class="btn btn-primary" type="button">بازگشت</button>
    </a>
{% endblock %}

olympiad_manager/templates/olympiad/exam_results.html
{% extends  "base.html" %}
{% load static %}


{% block title %}نتایج{% endblock %}
{% block content%}
    <h1>{{title}}</h1>
    <table class="table table-hover table-striped">
        <thead>
        <th>ردیف</th>
        <th>نام و نام‌خانوادگی</th>
        {% for i in problems %}
            <th>سوال {{i}}</th>
        {% endfor %}
        <th>مجموع</th>
        </thead>
    {% for total_score in total_scores %}
        <tr>
            <td>{{forloop.counter}}</td>
            {% with grades|lookup:total_score.id as val %}
                <td>{{val.0}}</td>
                {% for score in val.1 %}
                    <td>{% if score is None %}--{% else %}{{score}} {% endif %}</td>
                {% endfor %}
            {% endwith %}
            <td>{{total_score.score}}</td>
        </tr>
    {% endfor %}
    </table>
    <a href="{{ back_url }}"><button type="button" class="btn btn-primary">بازگشت</button></a>
{% endblock %}

olympiad_manager/templates/olympiad/grade.html
{% extends  "base.html" %}
{% load static%}

{% block title %}
نمره دهی سوال
{% endblock %}

{% block content%}
 <form method="post">
     <table class="table table-hover table-striped">
         <tbody>
         <tr>
             <td>صورت سوال</td>
             <td>{{problem.text}}</td>
         </tr>
         <tr>
             <td>نمره</td>
             <td>{{problem.score}} </td>
         </tr>
         </tbody>
     </table>
    {% csrf_token %}
     {{ form.as_p }}
     <button class="btn btn-success" type="submit">ثبت</button>
 </form>
{% endblock %}

olympiad_manager/templates/olympiad/levels.html
{% extends  "base.html" %}
{% load static%}

{% block title %}
تراز مدال آوران
{% endblock %}

{% block content%}
 <form method="post">
    <h1>تراز مدال آوران</h1>
    {% csrf_token %}
     {{ form.as_p }}
     <button class="btn btn-success" type="submit">ثبت</button>
 </form>
{% endblock %}

olympiad_manager/templates/olympiad/m1m2date.html
{% extends  "base.html" %}
{% load static%}
{% load widget_tweaks %}
{% block static %}
    {{ block.super }}
    <script src="{% static 'olympiad_manager/addm2day.js' %}"></script>
{% endblock %}

{% block title %}آزمون های مرحله اول و دوم{% endblock %}

{% block content%}
    <h1>مرحله اول و دوم </h1>
 <form method="post" class="form-horizontal">
     {% csrf_token %}
        {{ form.m1_eid }}
        {{ form.m2_day_count }}
        {{ form.rname }}
        {{ form.yr }}
     <h3>مرحله اول</h3>
     <div class="form-group">
        <div class="col-sm-1">
            {{ form.m1_date.label_tag }}
        </div>
         {{ form.m1_date|add_class:'form-control'|add_class:'col-sm-3' }}
         <button type="button" onclick="location.href='{% url 'olympiad:problem:list' fname year form.m1_eid.value %}'" class="btn btn-default col-sm-offset-1">مدیریت سوال ها</button>
         <button type="button" onclick="location.href='{% url 'olympiad:problem:results' fname year form.m1_eid.value %}'" class="btn btn-default">مشاهده نتایج</button>
     </div>
     <div id="m2days">
         <h3>مرحله دوم</h3>
     {% for i in form %}
         {% if forloop.counter0 > 4 %}
             {% if forloop.counter|divisibleby:3 %}
                 <div class="row">
                     <label for="id_m2_{% widthratio forloop.counter|add:-7 3 1 %}_date" class="col-sm-1">تاریخ:</label>
                     <input class="col-sm-3 form-control" id="id_m2_{% widthratio forloop.counter|add:-10 3 1 %}_date" name="m2_{% widthratio forloop.counter|add:-7 3 1 %}_date" type="text" value="{{ i.value }}"/>
             {% elif forloop.counter0|divisibleby:3 %}
                     <label for="id_m2_{% widthratio forloop.counter|add:-7 3 1 %}_darsad" class="col-sm-1">درصد تاثیر:</label>
                     <input class="col-sm-3 form-control" id="id_m2_{% widthratio forloop.counter|add:-7 3 1 %}_darsad" name="m2_{% widthratio forloop.counter|add:-7 3 1 %}_darsad" type="number" value="{{ i.value }}"/>
             {% else %}
                     {{ i }}
                     <button type="button" class="btn btn-default col-sm-offset-1" onclick="location.href='{% url 'olympiad:problem:list' fname year i.value %}'">مدیریت سوال ها</button>
                     <button type="button" class="btn btn-default" onclick="location.href='{% url 'olympiad:problem:results' fname year i.value %}'">مشاهده نتایج</button>
                 </div>
                {% endif %}
         {% endif %}
     {% endfor %}
     </div>
    <br>
     <button class="btn btn-warning" id="add_m2_button" type="button">اضافه کردن روز مرحله دوم</button>
     <button class="btn btn-success" type="submit">ثبت</button>
     <button class="btn btn-primary" onclick="location.href='{% url 'olympiad:home' fname year %}'"type="button">بازگشت</button>
 </form>
{% endblock %}

olympiad_manager/templates/olympiad/medals.html
{% extends  "base.html" %}

{% block title %}نتایج{% endblock %}
{% block content%}
    <h1>مدال آوران طلا</h1>
    <table class="table table-hover table-striped">
        <thead>
        <th>ردیف</th>
        <th>کد ملی</th>
        <th>نام و نام‌خانوادگی</th>
        </thead>
    {% for q in gold %}
        <tr>
            <td style="background-color: gold;">{{forloop.counter}}</td>
            <td>{{q.id}}</td>
            <td>{{q.name}}</td>
        </tr>
    {% endfor %}
    </table>

    <h2>مدال آوران نقره</h2>
    <table class="table table-hover table-striped">
        <thead>
        <th>ردیف</th>
        <th>کد ملی</th>
        <th>نام و نام‌خانوادگی</th>
        </thead>
    {% for q in silver %}
        <tr>
            <td style="background-color: #e6e8fa;">{{forloop.counter}}</td>
            <td>{{q.id}}</td>
            <td>{{q.name}}</td>
        </tr>
    {% endfor %}
    </table>

    <h2>مدال آوران برنز</h2>
    <table class="table table-hover table-striped">
        <thead>
        <th>ردیف</th>
        <th>کد ملی</th>
        <th>نام و نام‌خانوادگی</th>
        </thead>
    {% for q in bronze %}
        <tr>
            <td style="background-color: #8c7853;">{{forloop.counter}}</td>
            <td>{{q.id}}</td>
            <td>{{q.name}}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

olympiad_manager/templates/olympiad/olympiad.html
{% extends "base.html" %}

    {% block title %} المپیاد {{fname}} {{year}}{% endblock %}
{% block content %}
       <div class="list-group">
       <h1>المپیاد {{fname}} سال {{year}}</h1>
       <a class="list-group-item" href="{% url 'olympiad:m1m2date' fname year %}"> مرحله اول و دوم</a>
       <br>
       <a class="list-group-item" href="{% url 'olympiad:course:list' fname year %}"> کلاس‌های دوره تابستانی</a>
       <br>
       <a class="list-group-item" href="{% url 'olympiad:summer-camp-exam:list' fname year %}"> آزمون‌های دوره تابستانی</a>
       <br>
       <a class="list-group-item" href="{% url 'olympiad:levels' fname year %}"> تراز مدال آوران</a>
       <br>
       <form method="post">
              {% csrf_token %}
              <button class="btn btn-success" type="submit">ثبت‌نام مدال‌آوران در بنیاد ملی نخبگان</button>
       </form>
              <br>
              <a class="btn btn-success" href="{% url 'olympiad:refresh-m2' fname year %}">اعمال نتایج مرحله دوم</a>
              <br>
              <br>
              <a class="btn btn-success" href="{% url 'olympiad:refresh-medal' fname year %}">اعمال مدال‌های طلا، نقره و برنز</a>

       </div>
{% endblock %}

olympiad_manager/templates/olympiad/problem.html
{% extends  "base.html" %}
{% load static%}

{% block content%}
 <form method="post">
     <h1>{{title}}</h1>
    {% csrf_token %}
     {{ form.as_p }}
     <button class="btn btn-success" type="submit">ثبت</button>
     <a href="{% url 'olympiad:problem:list' fname year eid %}">
        <button class="btn btn-primary" type="button">بازگشت</button>
     </a>
 </form>
{% endblock %}

olympiad_manager/templates/olympiad/problems.html
{% extends  "base.html" %}

{% block title %}امتحان{% endblock %}
{% block content%}
    <h1>مدیریت سوالات</h1>
    <table class="table table-hover table-striped">
        <thead>
        <th>شماره</th>
        <th>متن سوال</th>
        <th>نمره</th>
        <th>طراح</th>
        <th>اقدامات</th>
        </thead>
    {% for problem in problems %}
        <tr>
            <td>
            <a href="{% url 'olympiad:problem:edit' fname year eid problem.pnum%}">
                {{ forloop.counter }}
            </a>
            </td>
            <td>{{problem.text}}</td>
            <td>{{problem.score}}</td>
            <td>{{problem.name}}</td>
            <td><button type="button" class="btn btn-default" onclick="location.href='{% url 'olympiad:problem:graders' fname year eid problem.pnum %}'">مدیریت مصححین</button></td>
        </tr>
    {% endfor %}
    </table>
    <a href="{% url 'olympiad:problem:add' fname year eid %}"><button type="button" class="btn btn-success">سوال جدید</button></a>
    <a href="{{ back_url }}"><button type="button" class="btn btn-primary">بازگشت</button></a>
{% endblock %}

olympiad_manager/templates/olympiad/results.html
{% extends  "base.html" %}

{% block title %}نتایج{% endblock %}
{% block content%}
    <h1>{{title}}</h1>
    <table class="table table-hover table-striped">
        <thead>
        <th>ردیف</th>
        <th>کد ملی</th>
        <th>نام و نام‌خانوادگی</th>
        </thead>
    {% for q in queryset %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{q.id}}</td>
            <td>{{q.name}}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

olympiad_manager/templates/olympiad/summer_exam.html
{% extends "base.html" %}
{% load static%}

{% block content%}
 <form method="post">
     <h1>{{title}}</h1>
     {% csrf_token %}
     {{ form.as_p }}
     <button class="btn btn-success" type="submit">ثبت</button>
     <a href="{% url 'olympiad:summer-camp-exam:list' fname year %}">
        <button class="btn btn-primary" type="button">بازگشت</button>
     </a>

 </form>
{% endblock %}